"""
database.py — Shield Matrix Engine
All database operations. SQLite, no ORM, pure SQL.
"""

import sqlite3
import json
import os
from datetime import datetime

DB_PATH = os.environ.get("DB_PATH", "shield_matrix.db")


def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """Create all tables if they don't exist."""
    conn = get_conn()
    c = conn.cursor()

    # All WC2026 fixtures (source of truth)
    c.execute("""
    CREATE TABLE IF NOT EXISTS fixtures (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        match_id    TEXT UNIQUE,          -- e.g. "2026-06-11-MEX-RSA"
        date        TEXT NOT NULL,
        time_utc    TEXT,
        home_team   TEXT NOT NULL,
        away_team   TEXT NOT NULL,
        group_name  TEXT,
        venue       TEXT,
        round       TEXT,
        status      TEXT DEFAULT 'UPCOMING',  -- UPCOMING / LIVE / FINISHED
        home_score  INTEGER,
        away_score  INTEGER,
        ht_home     INTEGER,
        ht_away     INTEGER,
        goals_json  TEXT,                 -- JSON list of goal events
        updated_at  TEXT
    )""")

    # Predictions generated by the engine
    c.execute("""
    CREATE TABLE IF NOT EXISTS predictions (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        match_id        TEXT NOT NULL,
        home_team       TEXT NOT NULL,
        away_team       TEXT NOT NULL,
        match_date      TEXT NOT NULL,
        home_win_pct    REAL,
        draw_pct        REAL,
        away_win_pct    REAL,
        home_xg         REAL,
        away_xg         REAL,
        over25_pct      REAL,
        under25_pct     REAL,
        btts_yes_pct    REAL,
        btts_no_pct     REAL,
        top_scorelines  TEXT,             -- JSON
        best_bet        TEXT,
        best_bet_pct    REAL,
        confidence      TEXT,
        created_at      TEXT,
        FOREIGN KEY (match_id) REFERENCES fixtures(match_id)
    )""")

    # Team strength ratings (updated from real WC2026 results)
    c.execute("""
    CREATE TABLE IF NOT EXISTS team_stats (
        team_name   TEXT PRIMARY KEY,
        played      INTEGER DEFAULT 0,
        wins        INTEGER DEFAULT 0,
        draws       INTEGER DEFAULT 0,
        losses      INTEGER DEFAULT 0,
        goals_for   INTEGER DEFAULT 0,
        goals_against INTEGER DEFAULT 0,
        points      INTEGER DEFAULT 0,
        avg_gf      REAL DEFAULT 0.0,
        avg_ga      REAL DEFAULT 0.0,
        group_name  TEXT,
        updated_at  TEXT
    )""")

    conn.commit()
    conn.close()
    print("[DB] Tables ready.")


# ── FIXTURES ────────────────────────────────────────────────────────────────

def upsert_fixture(f: dict):
    conn = get_conn()
    c = conn.cursor()
    c.execute("""
    INSERT INTO fixtures
        (match_id, date, time_utc, home_team, away_team, group_name, venue, round,
         status, home_score, away_score, ht_home, ht_away, goals_json, updated_at)
    VALUES
        (:match_id,:date,:time_utc,:home_team,:away_team,:group_name,:venue,:round,
         :status,:home_score,:away_score,:ht_home,:ht_away,:goals_json,:updated_at)
    ON CONFLICT(match_id) DO UPDATE SET
        status      = excluded.status,
        home_score  = excluded.home_score,
        away_score  = excluded.away_score,
        ht_home     = excluded.ht_home,
        ht_away     = excluded.ht_away,
        goals_json  = excluded.goals_json,
        updated_at  = excluded.updated_at
    """, f)
    conn.commit()
    conn.close()


def get_fixtures_today(today: str) -> list:
    conn = get_conn()
    rows = conn.execute(
        "SELECT * FROM fixtures WHERE date = ? ORDER BY time_utc", (today,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_fixtures_upcoming(from_date: str, limit: int = 20) -> list:
    conn = get_conn()
    rows = conn.execute(
        "SELECT * FROM fixtures WHERE date >= ? AND status = 'UPCOMING' ORDER BY date, time_utc LIMIT ?",
        (from_date, limit)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_fixtures_finished() -> list:
    conn = get_conn()
    rows = conn.execute(
        "SELECT * FROM fixtures WHERE status = 'FINISHED' ORDER BY date DESC"
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_fixture_by_id(match_id: str) -> dict:
    conn = get_conn()
    row = conn.execute(
        "SELECT * FROM fixtures WHERE match_id = ?", (match_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


# ── PREDICTIONS ─────────────────────────────────────────────────────────────

def upsert_prediction(p: dict):
    conn = get_conn()
    conn.execute("""
    INSERT OR REPLACE INTO predictions
        (match_id, home_team, away_team, match_date,
         home_win_pct, draw_pct, away_win_pct,
         home_xg, away_xg,
         over25_pct, under25_pct, btts_yes_pct, btts_no_pct,
         top_scorelines, best_bet, best_bet_pct, confidence, created_at)
    VALUES
        (:match_id,:home_team,:away_team,:match_date,
         :home_win_pct,:draw_pct,:away_win_pct,
         :home_xg,:away_xg,
         :over25_pct,:under25_pct,:btts_yes_pct,:btts_no_pct,
         :top_scorelines,:best_bet,:best_bet_pct,:confidence,:created_at)
    """, p)
    conn.commit()
    conn.close()


def get_prediction(match_id: str) -> dict:
    conn = get_conn()
    row = conn.execute(
        "SELECT * FROM predictions WHERE match_id = ?", (match_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


# ── TEAM STATS ──────────────────────────────────────────────────────────────

def rebuild_team_stats():
    """Recompute all team stats from finished fixtures."""
    conn = get_conn()
    finished = conn.execute(
        "SELECT * FROM fixtures WHERE status = 'FINISHED'"
    ).fetchall()

    stats = {}
    groups = {}

    for m in finished:
        h, a = m["home_team"], m["away_team"]
        gh, ga = m["home_score"], m["away_score"]
        grp = m["group_name"] or ""

        for t in [h, a]:
            if t not in stats:
                stats[t] = {"played":0,"wins":0,"draws":0,"losses":0,"gf":0,"ga":0}
            groups[t] = grp

        stats[h]["played"] += 1; stats[h]["gf"] += gh; stats[h]["ga"] += ga
        stats[a]["played"] += 1; stats[a]["gf"] += ga; stats[a]["ga"] += gh

        if gh > ga:
            stats[h]["wins"] += 1; stats[a]["losses"] += 1
        elif gh == ga:
            stats[h]["draws"] += 1; stats[a]["draws"] += 1
        else:
            stats[a]["wins"] += 1; stats[h]["losses"] += 1

    now = datetime.utcnow().isoformat()
    for team, s in stats.items():
        pts = s["wins"] * 3 + s["draws"]
        p = s["played"]
        conn.execute("""
        INSERT OR REPLACE INTO team_stats
            (team_name, played, wins, draws, losses, goals_for, goals_against,
             points, avg_gf, avg_ga, group_name, updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
        """, (team, p, s["wins"], s["draws"], s["losses"],
              s["gf"], s["ga"], pts,
              round(s["gf"]/p, 2) if p else 0,
              round(s["ga"]/p, 2) if p else 0,
              groups.get(team,""), now))

    conn.commit()
    conn.close()


def get_standings() -> dict:
    conn = get_conn()
    rows = conn.execute(
        "SELECT * FROM team_stats ORDER BY group_name, points DESC, goals_for DESC"
    ).fetchall()
    conn.close()

    groups = {}
    for r in rows:
        r = dict(r)
        g = r["group_name"] or "Other"
        if g not in groups:
            groups[g] = []
        groups[g].append(r)
    return groups


def get_team_stat(team: str) -> dict:
    conn = get_conn()
    row = conn.execute(
        "SELECT * FROM team_stats WHERE team_name = ?", (team,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None
